### ISSUE TITLE
Using fields with a 'dot' in object key

### ISSUE THREAD

**Issue by paulhuisman** [xaksis/vue-good-table#593]
### Issue Type
- [x] Question

### Specs
What version are you using?
2.18.0

What browser?
Chrome

### Description
I have an array with objects that contain the following data:
```
0:
  id: (...)
  planned_start_date: (...)
  production.rec_name: (...)
```

As you can see some object keys contain a dot. When i add these keys to my columns in Vue-Good-Table **it does not show the value** inside `production.rec_name`:

```
columns: [
        {
          label: 'MO #',
          field: 'production.rec_name',
          type: 'string',
          sortable: false
        }
]
```

Is there a solution for this?
