### ISSUE TITLE
Change link color

### ISSUE THREAD

**Issue by picbenoit** [xaksis/vue-good-table#734]
### Issue Type (delete the irrelevant ones) 

- [x] Bug
- [] Enhancement Request
- [x] Question

Hi, I tried to change the chevron color and I wanted to override sass variable ($link-color) for that but does not work.

Here an example of my main sass file :

```
// Vue-good-table
$link-color: pink;
@import "vue-good-table/src/styles/style.scss";
```

Is anyone know why this solution not work and how to do ?

Thank you for this awesome lib !

Ben

**Comment by xaksis** [comment]
hey @picbenoit, VGT currently doesn't allow overriding Scss variables. But you can override the chevron color in your component:
```scss
/deep/ thead th{
   &.sorting-asc{
      &:after{
        border-bottom-color: <your color>;
      }
    }
    &.sorting-desc {
      &:before{
        border-top-color: <your color>;
      }
    }
}
```

closing.
