### ISSUE TITLE
Not fully supported for RTL language

### ISSUE THREAD

**Issue by larbi-asmaoui** [xaksis/vue-good-table#964]
Hi,

I want to enable rtl  mode but the text comes above the chevron buttons 
![Screenshot from 2023-07-08 16-44-51](https://github.com/xaksis/vue-good-table/assets/103370123/85a49471-98a3-46f5-8c9e-32dbeda4f08b)

**Comment by mohammadali-yazdani** [comment]
Hello dear

It can be solved in the traditional way.

```CSS
.vgt-table th.sortable button:after,
.vgt-table th.sortable button:before {
	right: unset;
	left: 6px;
}
```
